#!/bin/bash
bl_path="/sys/class/backlight/amdgpu_bl1/brightness"

current_brightness=$(cat $bl_path)
min_brightness=2

brightness_increment=25
min_brightness=0
max_brightness=255

case $1 in
	up)
		if [[ $(expr $current_brightness + $brightness_increment) -ge $max_brightness ]]; then
			new_brightness=$max_brightness
		else
			new_brightness=$(expr $current_brightness + 25)
		fi
		echo $new_brightness > $bl_path
		;;
	down)
		if [[ $(expr $current_brightness - $brightness_increment) -le $min_brightness ]]; then
			new_brightness=$min_brightness
		else
			new_brightness=$(expr $current_brightness - 25)
		fi
		echo $new_brightness > $bl_path
		;;
	*)
		;;
esac

